import { createFileRoute, Link } from "@tanstack/react-router";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { userSession } from "@/lib/session";
import { Button } from "@/components/ui/button";
import { QuestionTimer } from "@/components/quiz/QuestionTimer";
import { toast } from "sonner";

export const Route = createFileRoute("/quiz/$slug")({ component: QuizPage });
type Program={id:string;title:string;description:string|null;seconds_per_question:number;is_active:boolean};
type Question={question_id:string;question_text:string;option_a:string;option_b:string;option_c:string;option_d:string;question_position:number};
type Answer={questionId:string;selectedOption:string;timeMs:number};
function shuffled<T>(values:T[]){return [...values].sort(()=>Math.random()-.5)}

function QuizPage(){
 const {slug}=Route.useParams(); const session=userSession.get(); const [program,setProgram]=useState<Program|null>(null); const [questions,setQuestions]=useState<Question[]>([]); const [existing,setExisting]=useState<{score:number;total_ms:number}|null>(null); const [started,setStarted]=useState(false); const [index,setIndex]=useState(0); const [answers,setAnswers]=useState<Answer[]>([]); const [result,setResult]=useState<{score:number;rank:number;totalMs:number}|null>(null); const startedAt=useRef(Date.now());
 useEffect(()=>{void(async()=>{const {data:p}=await supabase.from("programs").select("id,title,description,seconds_per_question,is_active").eq("slug",slug).maybeSingle(); if(!p)return; setProgram(p); const {data:q}=await supabase.rpc("get_quiz_questions",{p_slug:slug}); setQuestions(shuffled((q??[]) as Question[])); if(session){const {data:a}=await supabase.from("attempts").select("score,total_ms").eq("program_id",p.id).eq("user_id",session.userId).maybeSingle();setExisting(a)}})()},[slug,session?.userId]);
 const finish=useCallback(async(finalAnswers:Answer[])=>{if(!program||!session)return; const totalMs=finalAnswers.reduce((sum,a)=>sum+a.timeMs,0); const {data,error}=await supabase.rpc("submit_quiz_attempt",{p_program_id:program.id,p_user_id:session.userId,p_answers:finalAnswers,p_total_ms:totalMs}); if(error)return toast.error(error.message); const row=data?.[0]; if(row)setResult({score:row.final_score,rank:Number(row.final_rank),totalMs:row.final_total_ms});},[program,session]);
 const answer=useCallback((selectedOption:string)=>{if(!program)return; const current=questions[index]; if(!current)return; const next=[...answers,{questionId:current.question_id,selectedOption,timeMs:Math.min(Date.now()-startedAt.current,program.seconds_per_question*1000)}]; setAnswers(next); if(index===questions.length-1){void finish(next)}else{setIndex(index+1);startedAt.current=Date.now()}},[answers,index,program,questions,finish]);
 const expire=useCallback(()=>answer(""),[answer]); const current=questions[index]; const options=useMemo(()=>current?(["a","b","c","d"] as const).map(k=>({key:k,text:current[`option_${k}`]})):[],[current]);
 if(!program)return <main className="grid min-h-screen place-items-center bg-muted"><p>Quiz not found.</p></main>;
 if(!session)return <main className="grid min-h-screen place-items-center bg-muted p-6"><section className="max-w-md rounded-2xl border bg-card p-8 text-center"><h1 className="text-2xl font-bold">Sign in to participate</h1><p className="my-4 text-muted-foreground">Only registered candidates can attend this competition.</p><Button asChild><Link to="/signin" search={{next:`/quiz/${slug}`}}>Sign in with mobile</Link></Button></section></main>;
 const summary=existing?{score:existing.score,totalMs:existing.total_ms,rank:null}:result?{...result}:null;
 if(summary)return <main className="grid min-h-screen place-items-center bg-muted p-6"><section className="w-full max-w-md rounded-2xl border bg-card p-8 text-center"><p className="text-sm font-semibold text-primary">ATTEMPT COMPLETE</p><h1 className="mt-3 text-3xl font-bold">{program.title}</h1><div className="my-8 grid grid-cols-2 gap-3"><div className="rounded-xl bg-muted p-4"><p className="text-sm text-muted-foreground">Score</p><p className="text-3xl font-bold">{summary.score}/{questions.length}</p></div><div className="rounded-xl bg-muted p-4"><p className="text-sm text-muted-foreground">Time</p><p className="text-3xl font-bold">{(summary.totalMs/1000).toFixed(1)}s</p></div></div>{summary.rank&&<p className="text-lg">Your rank: <strong>#{summary.rank}</strong></p>}</section></main>;
 if(!started)return <main className="grid min-h-screen place-items-center bg-muted p-6"><section className="w-full max-w-xl rounded-2xl border bg-card p-8"><span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold text-primary">QUIZ COMPETITION</span><h1 className="mt-5 text-4xl font-bold">{program.title}</h1><p className="mt-3 text-muted-foreground">{program.description}</p><div className="my-7 flex gap-8 border-y py-5"><div><strong>{questions.length}</strong><p className="text-sm text-muted-foreground">Questions</p></div><div><strong>{program.seconds_per_question}s</strong><p className="text-sm text-muted-foreground">Each question</p></div><div><strong>1</strong><p className="text-sm text-muted-foreground">Attempt only</p></div></div><Button size="lg" disabled={!program.is_active||!questions.length} onClick={()=>{setStarted(true);startedAt.current=Date.now()}}>Start competition</Button></section></main>;
 return <main className="grid min-h-screen place-items-center bg-muted p-6"><section className="w-full max-w-2xl rounded-2xl border bg-card p-7"><header className="flex items-center justify-between"><div><p className="text-sm text-muted-foreground">Question {index+1} of {questions.length}</p><div className="mt-2 h-2 w-48 overflow-hidden rounded-full bg-muted"><div className="h-full bg-primary" style={{width:`${((index+1)/questions.length)*100}%`}}/></div></div><QuestionTimer seconds={program.seconds_per_question} resetKey={index} onExpire={expire}/></header><h1 className="my-8 text-2xl font-semibold">{current?.question_text}</h1><div className="grid gap-3">{options.map(o=><Button key={o.key} variant="outline" className="h-auto justify-start whitespace-normal p-4 text-left" onClick={()=>answer(o.key)}><span className="grid size-7 shrink-0 place-items-center rounded-full bg-muted font-bold">{o.key.toUpperCase()}</span>{o.text}</Button>)}</div></section></main>;
}