/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizSlugRouteImport } from './routes/quiz.$slug'
import { Route as AdminProgramIdRouteImport } from './routes/admin_.program.$id'
import { Route as AdminProgramIdResultsRouteImport } from './routes/admin_.program.$id_.results'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizSlugRoute = QuizSlugRouteImport.update({
  id: '/quiz/$slug',
  path: '/quiz/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProgramIdRoute = AdminProgramIdRouteImport.update({
  id: '/admin_/program/$id',
  path: '/admin/program/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProgramIdResultsRoute = AdminProgramIdResultsRouteImport.update({
  id: '/admin_/program/$id_/results',
  path: '/admin/program/$id/results',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/super-admin': typeof SuperAdminRoute
  '/welcome': typeof WelcomeRoute
  '/quiz/$slug': typeof QuizSlugRoute
  '/admin/program/$id': typeof AdminProgramIdRoute
  '/admin/program/$id/results': typeof AdminProgramIdResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/super-admin': typeof SuperAdminRoute
  '/welcome': typeof WelcomeRoute
  '/quiz/$slug': typeof QuizSlugRoute
  '/admin/program/$id': typeof AdminProgramIdRoute
  '/admin/program/$id/results': typeof AdminProgramIdResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/super-admin': typeof SuperAdminRoute
  '/welcome': typeof WelcomeRoute
  '/quiz/$slug': typeof QuizSlugRoute
  '/admin_/program/$id': typeof AdminProgramIdRoute
  '/admin_/program/$id_/results': typeof AdminProgramIdResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/signin'
    | '/signup'
    | '/super-admin'
    | '/welcome'
    | '/quiz/$slug'
    | '/admin/program/$id'
    | '/admin/program/$id/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/signin'
    | '/signup'
    | '/super-admin'
    | '/welcome'
    | '/quiz/$slug'
    | '/admin/program/$id'
    | '/admin/program/$id/results'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/signin'
    | '/signup'
    | '/super-admin'
    | '/welcome'
    | '/quiz/$slug'
    | '/admin_/program/$id'
    | '/admin_/program/$id_/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  SuperAdminRoute: typeof SuperAdminRoute
  WelcomeRoute: typeof WelcomeRoute
  QuizSlugRoute: typeof QuizSlugRoute
  AdminProgramIdRoute: typeof AdminProgramIdRoute
  AdminProgramIdResultsRoute: typeof AdminProgramIdResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$slug': {
      id: '/quiz/$slug'
      path: '/quiz/$slug'
      fullPath: '/quiz/$slug'
      preLoaderRoute: typeof QuizSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/program/$id': {
      id: '/admin_/program/$id'
      path: '/admin/program/$id'
      fullPath: '/admin/program/$id'
      preLoaderRoute: typeof AdminProgramIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/program/$id_/results': {
      id: '/admin_/program/$id_/results'
      path: '/admin/program/$id/results'
      fullPath: '/admin/program/$id/results'
      preLoaderRoute: typeof AdminProgramIdResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  SuperAdminRoute: SuperAdminRoute,
  WelcomeRoute: WelcomeRoute,
  QuizSlugRoute: QuizSlugRoute,
  AdminProgramIdRoute: AdminProgramIdRoute,
  AdminProgramIdResultsRoute: AdminProgramIdResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
