// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbwiitijldyqvsnszbsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJid2lpdGlqbGR5cXZzbnN6YnNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODExMTQ3NDcsImV4cCI6MjA5NjY5MDc0N30.Aps38vDUC2eytew9IV55MpWeaBeQMEoYI47w2LgOnZ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});